### ISSUE TITLE
Deselected columns are included when generating the mini model from script

### ISSUE THREAD

**Issue by evaverbeke** [m-kovalsky/MiniModelBuilder#1]
Hi,

I want to make a mini model through the interface, and I select only a subset of columns from a certain table. In the model, this is correct, only the selected columns are included in the perspective.

However, the generated script includes Model.Tables["_table name_"].InPerspective[perspName] = true;, followed by a statement for each included column. However, the entire table seems to be added to the perspective due to this first statement, including the deselected columns. So when I try to recreate the mini model using the script, it differs from the mini model that was created through the interface, since it includes too many columns.

Is this the expected behaviour? Is there a way to bypass this, or am I overlooking a step to fix this?

A second issue is the fact that hidden columns don't show up in step 1 in the interface, meaning I can't choose to include/exclude these in the mini model, and they seem to be added automatically via the script (due to the problem described earlier), or excluded automatically through the interface. 

Is there a way to avoid this, or should I add/remove them to/from the perspective manually using a script?

Many thanks,
Eva

**Comment by m-kovalsky** [comment]
The issue has been resolved in version [1.0.4](https://github.com/m-kovalsky/MiniModelBuilder/releases/tag/1.0.4). Regarding the second issue you raised - this is on purpose as the tool detects dependent objects (columns, measures) and adds them to the mini model (perspective). This way, you don't need to remember to add all the foreign keys and dependent measures (as was the case before this tool) which is quite a lot of work.

**Comment by evaverbeke** [comment]
Thanks for the quick response and fix!

For the second issue, I indeed thought that was the case, but in combination with the first issue, this lead to some unexpected results, with all hidden columns being added anyway, regardlesso of dependency, after running the script. 

Best,
Eva

**Comment by evaverbeke** [comment]
Hi,

I wanted to make an additional remark. It seems that hidden columns that are used as SortByColumn for another column aren't automatically included as dependent objects. Is this by design?

Best,
Eva

**Comment by m-kovalsky** [comment]
If you can outline a specific case where you get 'unexpected results' with dependencies, please detail them. Then I can more efficiently fix the issue.

SortByColumn dependency has been resolved in [1.0.5](https://github.com/m-kovalsky/MiniModelBuilder/releases/tag/1.0.5)

**Comment by evaverbeke** [comment]
The only unexpected result that was left after the fix in 1.04 were the SortByColumns. Thanks for fixing this!
